### ISSUE TITLE
Change maintainer

### ISSUE THREAD

**Issue by adelevie** [dpp/lawyersongithub#22]
Hey @dpp,

It looks like things haven't been too active here even though there's a few un-addressed pull requests. I'd be happy to maintain/administer this repo.

I think since this project has started, many, many more lawyers have started using GitHub. In fact, I'm helping organize a [meetup group in DC](https://github.com/dclegalhackers) that is seeking to do just that.

Let me know!

**Comment by dazzaji** [comment]
speaking of "Change maintainer"... 

It looks like things haven't been too active here even though there's a few un-addressed pull requests. I'd be happy to help maintain/administer this repo.

I think since this project has started, many, many more lawyers have started using GitHub. In fact, I'm helping [organize or participate in several groups](https://gist.github.com/dazzaji/b80eb13146eb33ebe746199ac13dffcc) using GitHub for law.
